### ISSUE TITLE
I'm having trouble getting the module to load. I'm sure I'm just doing something wrong.

### ISSUE THREAD

**Issue by Darkwingduc** [ferferga/MMM-GoogleCast#13]
`
Scanning Google Cast devices inside your network...
DEVICE 0
--------------------
Name: Home group
Type: group
ID: bb62adef-2deb-477f-b10e-adaeaf31ea48
--------------------
DEVICE 1
--------------------
Name: Living Room speaker
Type: audio
ID: c4b70b26-1c4b-0d49-5741-d5f84dfab758
--------------------
DEVICE 2
--------------------
Name: TV
Type: cast
ID: 6bd87200-712c-1da8-e566-a8a1854b1aee
--------------------
`
`                {
                        module: 'MMM-GoogleCast',
                        position: "top_left",
                        classes: "default everyone",
                        header: "Google Cast",
                        config: {
                                device: "c4b70b26-1c4b-0d49-5741-d5f84dfab758",
                        }
                },
`
`npm start

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-04-19 14:57:39.613] [LOG]    Starting MagicMirror: v2.11.0
[2020-04-19 14:57:39.627] [LOG]    Loading config ...
[2020-04-19 14:57:39.638] [LOG]    Loading module helpers ...
[2020-04-19 14:57:39.642] [LOG]    No helper found for module: alert.
[2020-04-19 14:57:39.697] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:39.699] [LOG]    Module helper loaded: updatenotification
[2020-04-19 14:57:39.702] [LOG]    No helper found for module: clock.
[2020-04-19 14:57:40.548] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.550] [LOG]    Module helper loaded: calendar
[2020-04-19 14:57:40.551] [LOG]    No helper found for module: compliments.
[2020-04-19 14:57:40.553] [LOG]    No helper found for module: currentweather.
[2020-04-19 14:57:40.589] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.590] [LOG]    Module helper loaded: newsfeed
[2020-04-19 14:57:40.596] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'python-shell'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[2020-04-19 14:57:40.598] [LOG]    Loading module helpers ...
[2020-04-19 14:57:40.600] [LOG]    No helper found for module: alert.
[2020-04-19 14:57:40.602] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.603] [LOG]    Module helper loaded: updatenotification
[2020-04-19 14:57:40.605] [LOG]    No helper found for module: clock.
[2020-04-19 14:57:40.606] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.606] [LOG]    Module helper loaded: calendar
[2020-04-19 14:57:40.607] [LOG]    No helper found for module: compliments.
[2020-04-19 14:57:40.609] [LOG]    No helper found for module: currentweather.
[2020-04-19 14:57:40.610] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.610] [LOG]    Module helper loaded: newsfeed
[2020-04-19 14:57:40.613] [ERROR]  App threw an error during load
[2020-04-19 14:57:40.615] [ERROR]  Error: Cannot find module 'python-shell'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2020-04-19 14:57:40.619] [LOG]    Whoops! There was an uncaught exception...
[2020-04-19 14:57:40.620] [ERROR]  Error: Cannot find module 'python-shell'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[2020-04-19 14:57:40.632] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-04-19 14:57:40.634] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[2020-04-19 14:57:40.730] [LOG]    Launching application.
> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-04-19 14:57:39.613] [LOG]    Starting MagicMirror: v2.11.0
[2020-04-19 14:57:39.627] [LOG]    Loading config ...
[2020-04-19 14:57:39.638] [LOG]    Loading module helpers ...
[2020-04-19 14:57:39.642] [LOG]    No helper found for module: alert.
[2020-04-19 14:57:39.697] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:39.699] [LOG]    Module helper loaded: updatenotification
[2020-04-19 14:57:39.702] [LOG]    No helper found for module: clock.
[2020-04-19 14:57:40.548] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.550] [LOG]    Module helper loaded: calendar
[2020-04-19 14:57:40.551] [LOG]    No helper found for module: compliments.
[2020-04-19 14:57:40.553] [LOG]    No helper found for module: currentweather.
[2020-04-19 14:57:40.589] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.590] [LOG]    Module helper loaded: newsfeed
[2020-04-19 14:57:40.596] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'python-shell'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[2020-04-19 14:57:40.598] [LOG]    Loading module helpers ...
[2020-04-19 14:57:40.600] [LOG]    No helper found for module: alert.
[2020-04-19 14:57:40.602] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.603] [LOG]    Module helper loaded: updatenotification
[2020-04-19 14:57:40.605] [LOG]    No helper found for module: clock.
[2020-04-19 14:57:40.606] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.606] [LOG]    Module helper loaded: calendar
[2020-04-19 14:57:40.607] [LOG]    No helper found for module: compliments.
[2020-04-19 14:57:40.609] [LOG]    No helper found for module: currentweather.
[2020-04-19 14:57:40.610] [LOG]    Initializing new module helper ...
[2020-04-19 14:57:40.610] [LOG]    Module helper loaded: newsfeed
[2020-04-19 14:57:40.613] [ERROR]  App threw an error during load
[2020-04-19 14:57:40.615] [ERROR]  Error: Cannot find module 'python-shell'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2020-04-19 14:57:40.619] [LOG]    Whoops! There was an uncaught exception...
[2020-04-19 14:57:40.620] [ERROR]  Error: Cannot find module 'python-shell'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleCast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Modu
`

**Comment by ferferga** [comment]
@Darkwingduc You forgot to run `npm install` in the MMM-GoogleCast folder

**Comment by Darkwingduc** [comment]
Thank you that did it. The one line install command didn't work for me so I had to split it up I must have missed that one.

**Comment by ferferga** [comment]
Good! @Darkwingduc

**Comment by ferferga** [comment]
What exactly failed in the one-line btw? @Darkwingduc
